### ISSUE TITLE
La configuración de compose no funciona

### ISSUE THREAD

**Issue by nicopaez** [joaquincasal/hemoclub#97]
Siguiendo los pasos que indica el README el contenedor WEB inicia y falla:

    hemoclub-web-1       | => Booting Puma
    hemoclub-web-1       | => Rails 7.1.3.4 application starting in development
    hemoclub-web-1       | => Run `bin/rails server --help` for more startup options
    hemoclub-web-1       |
    hemoclub-web-1       | Heads up! 🔥
    hemoclub-web-1       |
    hemoclub-web-1       | 👉 StimulusReflex requires caching to be enabled. Caching allows the session to be modified during ActionCable requests.
    hemoclub-web-1       |
    hemoclub-web-1       | To enable caching in development, run:
    hemoclub-web-1       |
    hemoclub-web-1       |   rails dev:cache
    hemoclub-web-1       |
    hemoclub-web-1       | To ignore any warnings and start the application anyway, you can set the SKIP_SANITY_CHECK environment variable:
    hemoclub-web-1       |
    hemoclub-web-1       |   SKIP_SANITY_CHECK=true rails
    hemoclub-web-1       |
    hemoclub-web-1       | To do this permanently, add the following directive to the StimulusReflex initializer:
    hemoclub-web-1       |
    hemoclub-web-1       |   StimulusReflex.configure do |config|
    hemoclub-web-1       |     config.on_failed_sanity_checks = :warn
    hemoclub-web-1       |   end
    hemoclub-web-1       |
    hemoclub-web-1       | Exiting
    hemoclub-web-1 exited with code 1

Luego al intentar conectarme con "docker compose exec -it web bash" indica:

    service "web" is not running

**Comment by joaquincasal** [comment]
Resuelto en c644a3a
